<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="2.425" tests="4" failures="4">
  <testsuite name="Root Suite" timestamp="2023-07-02T08:36:05" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Sample task tests" timestamp="2023-07-02T08:36:05" tests="4" file="D:\devel\github\azure_devops_versioning_tasks\_build\Tasks\CalculateNextVersionV1\tests\_suite.js" failures="4" time="2.425">
    <testcase name="Sample task tests should succeed with build from master" time="1.126" classname="should succeed with build from master">
      <failure><![CDATA[AssertionError [ERR_ASSERTION]: should have succeeded
    at Context.<anonymous> (D:\devel\github\azure_devops_versioning_tasks\_build\Tasks\CalculateNextVersionV1\tests\_suite.js:86:16)
    at callFnAsync (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:306:8)
    at Test.Runnable.run (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:261:7)
    at Runner.runTest (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:421:10)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:528:12
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:341:14)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:351:7
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:283:14)
    at Immediate._onImmediate (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:319:5)
    at processImmediate (internal/timers.js:461:21)]]></failure>
    </testcase>
    <testcase name="Sample task tests should succeed with build from feature branch" time="0.468" classname="should succeed with build from feature branch">
      <failure><![CDATA[AssertionError [ERR_ASSERTION]: should have succeeded
    at Context.<anonymous> (D:\devel\github\azure_devops_versioning_tasks\_build\Tasks\CalculateNextVersionV1\tests\_suite.js:104:16)
    at callFnAsync (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:306:8)
    at Test.Runnable.run (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:261:7)
    at Runner.runTest (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:421:10)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:528:12
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:341:14)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:351:7
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:283:14)
    at Immediate._onImmediate (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:319:5)
    at processImmediate (internal/timers.js:461:21)]]></failure>
    </testcase>
    <testcase name="Sample task tests should succeed with build from Pull request to master" time="0.444" classname="should succeed with build from Pull request to master">
      <failure><![CDATA[AssertionError [ERR_ASSERTION]: should have succeeded
    at Context.<anonymous> (D:\devel\github\azure_devops_versioning_tasks\_build\Tasks\CalculateNextVersionV1\tests\_suite.js:122:16)
    at callFnAsync (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:306:8)
    at Test.Runnable.run (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:261:7)
    at Runner.runTest (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:421:10)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:528:12
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:341:14)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:351:7
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:283:14)
    at Immediate._onImmediate (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:319:5)
    at processImmediate (internal/timers.js:461:21)]]></failure>
    </testcase>
    <testcase name="Sample task tests should succeed with build from release branch" time="0.387" classname="should succeed with build from release branch">
      <failure><![CDATA[AssertionError [ERR_ASSERTION]: should have succeeded
    at Context.<anonymous> (D:\devel\github\azure_devops_versioning_tasks\_build\Tasks\CalculateNextVersionV1\tests\_suite.js:140:16)
    at callFnAsync (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:306:8)
    at Test.Runnable.run (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runnable.js:261:7)
    at Runner.runTest (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:421:10)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:528:12
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:341:14)
    at D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:351:7
    at next (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:283:14)
    at Immediate._onImmediate (D:\devel\github\azure_devops_versioning_tasks\node_modules\mocha\lib\runner.js:319:5)
    at processImmediate (internal/timers.js:461:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>